version: '3'

networks:
  lumens:

services:
  app:
    container_name: lumen-app
    image: lumen-app
    ports:
      - "8080:80"
    networks:
      - lumens
  
  mysql:
    container_name: mysql
    image: mysql:5.7.37
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - lumens
    environment:
      MYSQL_DATABASE: "lumen_api"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      SERVICE_TAGS: "dev"
      SERVICE_NAME: "mysql"

